include:
  - project: 'AgileFactory/Witboost.Mesh/witboost.Mesh.CI'
    ref: 'main'
    file: 'common/witboost.helm.gitlab-ci.yml'

image: registry.gitlab.com/agilefactory/witboost.mesh/provisioning/cdp/cicd/scala-sbt

stages:
  - setup
  - check
  - compile
  - test
  - build
  - package

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"

cache:
  untracked: true
  paths:
    - "sbt-cache/ivy/cache"
    - "sbt-cache/boot"
    - "sbt-cache/sbtboot"
    - "sbt-cache/target"

setup:
  stage: setup
  extends: .witboost.helm.base-job
  cache: []
  before_script: []
  script:
    - !reference [.witboost.helm.clone-scripts, script]
    - !reference [.witboost.helm.get-version, script]
    - echo "VERSION=${VERSION}" >> vars.env
  artifacts:
    reports:
      dotenv: vars.env

witboost.helm.checks:
  stage: check
  extends: .witboost.helm.base-job
  before_script: []
  cache: []
  script:
    - !reference [.witboost.helm.clone-scripts, script]
    - !reference [.witboost.helm.checks, script]
  variables:
    CHART_FOLDER: helm

check:
  stage: check
  script:
    - sbt scalafmtSbtCheck scalafmtCheckAll ${SBT_OPTS}

compile:
  stage: compile
  script:
    - sbt compile ${SBT_OPTS}

test:
  stage: test
  script:
    - sbt clean coverage test coverageAggregate ${SBT_OPTS}
  coverage: '/Statement coverage[A-Za-z\.*]\s*:\s*([^%]+)/'
  artifacts:
    paths:
      - target/scala-2.13/scoverage-report/*
      - target/scala-2.13/coverage-report/*
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/scala-2.13/coverage-report/cobertura.xml
      junit:
        - api/target/test-reports/TEST-*.xml
        - core/target/test-reports/TEST-*.xml
        - error-handler/target/test-reports/TEST-*.xml
        - service/target/test-reports/TEST-*.xml
        - quartz-embedded-scheduler/target/test-reports/TEST-*.xml

build:
  services:
    - docker:19.03.12-dind
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375
  script: |
    apt-get install -yqq curl
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo   "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable" |  tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update -yqq
    apt-get install -yqq docker-ce-cli
    docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    echo "VERSION: $VERSION"
    sbt clean compile k8tyGitlabCIPublish docker:publish ${SBT_OPTS}

witboost.helm.deploy:
  stage: package
  before_script: []
  cache: []
  extends: .witboost.helm.deploy
  #only:
  #  - master
  #  - tags
  #  - /(^release\/([0-9]+)\.([0-9]+))/