apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{- include "cdp-spark-provisioner.labels" . | nindent 4 }}
  name: {{ template "cdp-spark-provisioner.fullname" . }}-config
data:
  application.conf: |
  {{- if .Values.configOverride -}}
  {{- .Values.configOverride | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/application.conf" | nindent 4 }}
  {{ end }}
  logback.xml: |
  {{- if .Values.logbackOverride -}}
  {{- .Values.logbackOverride | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/logback.xml" | nindent 4 }}
  {{ end }}
  krb5.conf: |
  {{- if .Values.cdpPrivate.kerberos.krb5Override -}}
  {{- .Values.cdpPrivate.kerberos.krb5Override | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/krb5.conf" | nindent 4 }}
  {{ end }}
  jaas.conf: |
  {{- if .Values.cdpPrivate.kerberos.jaasOverride -}}
  {{- .Values.cdpPrivate.kerberos.jaasOverride | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/jaas.conf" | nindent 4 }}
  {{ end }}
  quartz.properties: |
  {{- if .Values.cdpPrivate.livy.quartzPropsOverride -}}
  {{- .Values.cdpPrivate.livy.quartzPropsOverride | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/quartz.properties" | nindent 4 }}
  {{ end }}