{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cdp-spark-provisioner.name" . }}-service-account
  annotations:
    eks.amazonaws.com/role-arn: {{ required "Role ARN is required" .Values.serviceAccount.roleArn }}
{{- end}}