addSbtPlugin("org.scalameta"   % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("org.wartremover" % "sbt-wartremover"     % "2.4.15")
addSbtPlugin("org.scoverage"   % "sbt-scoverage"       % "2.0.7")
addSbtPlugin("com.eed3si9n"    % "sbt-assembly"        % "2.1.4")
addSbtPlugin("dev.guardrail"   % "sbt-guardrail"       % "0.75.1")
addSbtPlugin("com.github.sbt"  % "sbt-native-packager" % "1.9.11")
addSbtPlugin("app.k8ty"        % "gitlab-plugin"       % "0.0.8")
