apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: "cdp-spark"
          valueMap:
            cdp-private-spark-keytab: keytab-base64
            cdp-private-spark-custom-ca: customca-base64
            #CDP_ACCESS_KEY_ID: aaa
            #CDP_PRIVATE_KEY: bbb
            #CDP_DEPLOY_ROLE_USER: ccc
            #CDP_DEPLOY_ROLE_PASSWORD: ddd