# Default values for python-specific-provisioner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Docker Registry Secret name used to access a private repo
dockerRegistrySecretName: regcred
# -- Allows you to specify common labels
labels: {}

image:
  # -- Image repository
  registry: registry.gitlab.com/agilefactory/witboost.mesh/provisioning/cdp-refresh/witboost.mesh.provisioning.workload.cdp.spark
  # -- Image tag
  tag: latest
  # -- The imagePullPolicy for a container and the tag of the image affect when the kubelet attempts to pull (download) the specified image.
  pullPolicy: Always

# -- service account nme
serviceAccount:
  create: true
  # -- The AWS role arn that will be assumed
  roleArn: asd

# -- the name of an existing serviceAccount
existingServiceAccount:

# -- the number of pod replicas
replicas: 1

# -- readiness probe spec
readinessProbe: {}

# -- liveliness probe spec
livenessProbe: {}

# -- security context spec
securityContext:
  runAsUser: 1001
  allowPrivilegeEscalation: false
  runAsNonRoot: true

# -- resources spec
resources: {}

# -- This configuration allows you to override the application.yaml file
configOverride:

# -- This configuration allows you to override the logback.xml file
logbackOverride: